version: '3.9'

services:
  db-cloud-library:
    image: mysql:latest
    container_name: db-cloud-library
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

  backend-cloud-library:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db-cloud-library:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=test
      - DATABASE_URL_TEST=mysql://root:12345678@db-cloud-library:3306/cloud-library-test?schema=public
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
