on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalando as dependências
        run: npm install

      - name: Executando o lint para verificar se há erros
        run: npx eslint . --ext .ts
